### ISSUE TITLE
Add some vim keybinds

### ISSUE THREAD

**Issue by ggrandi** [bautistaaa/typehero#399]
Keybinds I can think of (might add more):
- [x]  `K`: hover functionality (#403)
- [x] (tbd): code diagnostics (#434)
- [x] `gd`: goto definition (#434)
- [x] `gr`: goto references (#434)
- [x] `gi`: goto implementation (#434)

**Comment by QuiiBz** [comment]
We might want this one too:
- `gi`: goto implementation

**Comment by Hacksore** [comment]
# can we please have `gcc` added to block comment as a GFI?

@bautistaaa @ggrandi
